Basic EMax Skyline32 Acro board support
helo9/zephly pull request #24
Opened 2022-02-19 09:51 UTC by notoriou5

* Adding EMax skyline32 acro board
* Adding sample driver to read mpu6050 data

2022-02-19 11:32 UTC, helo9 requested changes
LaGTM ;)

The datasheet is a bit too big, I would say and found some stuff I did wrong, also present in your copy ;)

2022-03-27 11:32 UTC, notoriou5 commented on boards/arm/emax_skyline32/upload.jlink
> +Device STM32F103CB
I deleted it but did not open a PR for the CC3D yet

2022-03-27 11:32 UTC, notoriou5 commented on samples/drivers/mpu6050/src/main.c
> +    ret = i2c_reg_write_byte(i2c_dev, (uint16_t) 0x68, 0x6B, 0x00);
replaced :)

2022-03-27 11:32 UTC, notoriou5 commented on samples/drivers/mpu6050/src/main.c
> +
didn't change anything here yet...

2022-04-01 09:11 UTC, helo9 approved these changes

2022-04-01 12:08 UTC, merged